
set(OUTPATH_SUFFIX "/Debug")

if(${THE_PROJECT_PREFIX}_OS_WINDOWS)
	set(BIN_PATH ${CMAKE_ROOT_DIR}/bin/win)
	set(LIB_PATH ${CMAKE_ROOT_DIR}/lib/win)
elseif(${THE_PROJECT_PREFIX}_OS_MACOS)
	set(BIN_PATH ${CMAKE_ROOT_DIR}/bin/macos)
	set(LIB_PATH ${CMAKE_ROOT_DIR}/lib/macos)
elseif(${THE_PROJECT_PREFIX}_OS_IOS)
	set(BIN_PATH ${CMAKE_ROOT_DIR}/bin/ios)
	set(LIB_PATH ${CMAKE_ROOT_DIR}/lib/ios)
else()
	set(BIN_PATH ${CMAKE_ROOT_DIR}/bin/unkown${OUTPATH_SUFFIX})
	set(LIB_PATH ${CMAKE_ROOT_DIR}/lib/unkown${OUTPATH_SUFFIX})
endif()
